// Original definitions and examples written for this trainer.
window.ANALYSIS_DATA = {
 devices: [
 {id:'metaphor',name:'Metaphor',definition:'Describes one thing as another, transferring associations without making a literal claim.',contrast:'simile',distinction:'An image is presented as an identity rather than an explicit comparison.',examples:[
 ['In the editorial, rising rents are criticised.','For young tenants, the city has become |a locked door|.','The image presents access to city life as blocked, framing housing costs as exclusion rather than mere inconvenience.'],
 ['A student describes growing pressure before an exam.','Each new deadline added another stone to |the mountain on my desk|.','The image makes the workload seem vast and difficult to overcome, conveying the student’s sense of being overwhelmed.'],
 ['A speaker argues that libraries connect communities.','Our library is |a bridge between neighbours| who would otherwise never meet.','The bridge image represents the library as a connection across social separation, supporting the case for keeping it open.']]},
 {id:'simile',name:'Simile',definition:'Explicitly compares different things using a linking expression such as “like” or “as”.',contrast:'metaphor',distinction:'The comparison is explicitly signalled by “like” or “as”; those words alone do not always indicate a simile.',examples:[
 ['A narrator waits anxiously for a decision.','The minutes moved |like exhausted runners| towards the hour.','The comparison makes time seem painfully slow, conveying the narrator’s anxious waiting.'],
 ['A journalist describes how an unverified rumour spreads.','The rumour spread |like sparks across dry grass|.','The comparison stresses rapid spread and the potential for damage, framing the rumour as dangerous.'],
 ['A student recalls arriving at a welcoming school.','Her greeting felt |like sunlight through a closed curtain|.','The comparison associates the greeting with warmth and relief, suggesting that it interrupts the student’s isolation.']]},
 {id:'personification',name:'Personification',definition:'Gives human qualities or actions to something non-human or abstract.',contrast:'metaphor',distinction:'Human behaviour is attributed to something non-human. Personification can also be described as a kind of metaphor.',examples:[
 ['A narrator returns to an abandoned childhood home.','At the end of the lane, |the house watched me| through its broken windows.','Giving the house the ability to watch makes the return feel unsettling, as if the narrator is being judged by the past.'],
 ['A speaker criticises a town’s neglected industrial area.','Behind the station, |the forgotten factories begged for attention|.','The factories become figures in need, presenting neglect as something the town has a responsibility to address.'],
 ['A character is reluctant to reveal a secret.','Between us, |silence refused to leave|.','Giving silence a will of its own conveys how persistent the tension is and how difficult speaking feels.']]},
 {id:'anaphora',name:'Anaphora',definition:'Repeats a word or phrase at the beginning of successive clauses or sentences.',contrast:'parallelism',distinction:'The same opening words recur. Parallelism concerns repeated grammatical patterns; both can occur together.',examples:[
 ['A student speaker calls for equal access to school activities.','|We deserve a voice. We deserve a choice. We deserve a chance.|','The repeated opening presents participation as a shared entitlement, reinforcing the speaker’s collective demand.'],
 ['A narrator remembers a friend who has moved away.','|I remember the jokes. I remember the walks. I remember the last goodbye.|','The repeated opening accumulates memories and draws the passage towards the final separation, conveying persistent loss.'],
 ['An editorial challenges promises about safer cycling.','|They promised crossings. They promised lights. They promised change.|','The repeated opening gathers the authorities’ commitments together, preparing the reader to judge whether they have been fulfilled.']]},
 {id:'parallelism',name:'Parallelism',definition:'Repeats a grammatical structure across related phrases, clauses or sentences.',contrast:'anaphora',distinction:'The grammatical pattern recurs even if the opening words differ.',examples:[
 ['A student contrasts the roles of staff and learners.','|Teachers offered guidance; students offered ideas.|','The balanced structures give the two contributions comparable weight, presenting improvement as a shared undertaking.'],
 ['A report contrasts two neighbourhoods after a flood.','|Some families counted losses; other families counted profits.|','The matching structures foreground the unequal consequences of the same event, sharpening the report’s criticism.'],
 ['A narrator describes two siblings coping differently.','|Maya searched for answers; Leo searched for excuses.|','The repeated structure invites a comparison of the siblings’ attitudes, distinguishing responsibility from avoidance.']]},
 {id:'antithesis',name:'Antithesis',definition:'Places contrasting ideas close together, often in balanced structures.',contrast:'oxymoron',distinction:'Opposing ideas are contrasted across phrases or clauses; an oxymoron combines apparently contradictory terms within a compact expression.',examples:[
 ['A speech argues against unequal access to technology.','|A few gained convenience; many lost opportunity.|','The opposing outcomes emphasise unequal benefits, supporting the speaker’s demand for fairer access.'],
 ['An editorial criticises a leader’s response to a crisis.','|The speech offered certainty; the evidence offered doubt.|','The contrast exposes a gap between confident presentation and the available evidence, challenging the leader’s credibility.'],
 ['A character reflects on a move abroad.','|I had gained a home and lost a sense of belonging.|','The contrast separates having a place to live from feeling accepted, conveying the character’s divided experience.']]},
 {id:'hyperbole',name:'Hyperbole',definition:'Uses deliberate exaggeration beyond a literal, credible description.',contrast:'understatement',distinction:'The description amplifies rather than downplays the situation.',examples:[
 ['A narrator is frustrated by a slow school computer.','The login screen took |three centuries| to load.','The impossible timescale conveys impatience and gives a minor delay a humorous sense of enormity.'],
 ['A student complains about an overflowing bag.','I was carrying |every book ever printed| to the bus stop.','The exaggeration conveys the perceived burden and invites amusement at the student’s complaint.'],
 ['A teenager recalls an embarrassing mistake on stage.','I was certain |the entire planet had heard me| forget my lines.','The impossible audience conveys how overwhelming the embarrassment feels to the teenager, rather than its actual public reach.']]},
 {id:'understatement',name:'Understatement',definition:'Deliberately describes something as less serious, intense or significant than the context suggests.',contrast:'hyperbole',distinction:'The wording downplays a situation whose significance is established by the context.',examples:[
 ['A storm has destroyed the roof of a character’s home.','Looking at the wreckage, he called it |a slight inconvenience|.','The restrained wording clashes with the destruction, suggesting an attempt to maintain composure through dry humour.'],
 ['A runner has just won an international championship.','Asked about the race, she said it had gone |reasonably well|.','The modest assessment plays down an exceptional achievement, presenting the runner as restrained rather than boastful.'],
 ['A narrator has spent all night rebuilding a damaged project.','By morning I was |a little tired|.','The mild description contrasts with the exhausting night and creates a dry, self-controlled narrative voice.']]},
 {id:'litotes',name:'Litotes',definition:'Expresses an evaluation by negating its opposite, often as a form of understatement.',contrast:'understatement',distinction:'Negation of the opposite is the specific mechanism. Understatement is the broader category; the two labels can both apply.',examples:[
 ['A teacher praises a carefully researched student proposal.','This is |no careless piece of work|.','Negating carelessness offers restrained praise for the student’s effort, rather than using an openly enthusiastic compliment.'],
 ['An experienced climber recalls a dangerous ascent.','Reaching the summit was |no small achievement|.','Negating smallness stresses the scale of the achievement through restrained wording.'],
 ['A reviewer cautiously recommends a new novel.','The final chapter is |not without charm|.','The double negative gives qualified praise, suggesting approval while preserving the reviewer’s reserved tone.']]},
 {id:'oxymoron',name:'Oxymoron',definition:'Combines apparently contradictory terms in a compact expression.',contrast:'antithesis',distinction:'The contradiction is compressed into a phrase rather than developed as opposing statements.',examples:[
 ['A narrator describes distant relatives greeting one another formally.','Their reunion began with |friendly hostility|.','The contradictory qualities suggest that outward politeness conceals resentment, exposing tension in the relationship.'],
 ['A student reluctantly agrees to a plan.','I gave my |enthusiastic reluctance| the brightest smile I could manage.','The contradiction conveys a conflict between the student’s outward performance and inward resistance.'],
 ['A narrator describes life in a tightly controlled settlement.','We enjoyed |regulated freedom| within the painted lines.','Combining freedom with regulation questions how free the inhabitants really are, inviting criticism of the settlement’s rules.']]},
 {id:'rhetorical-question',name:'Rhetorical question',aliases:['rhetorical questions'],definition:'Uses the form of a question primarily to make a point or prompt reflection rather than request an answer.',contrast:'anaphora',distinction:'The context shows that the speaker is making a point rather than seeking information.',examples:[
 ['A speaker urges the council to protect a local park.','|What kind of town sells its children’s only playground?|','The question frames the sale as a moral failure and pressures councillors to consider their responsibility to children.'],
 ['An editorial challenges an empty promise of equal opportunity.','|How equal is a race when some runners begin miles ahead?|','The question invites readers to reject a simple claim of fairness by drawing attention to unequal starting conditions.'],
 ['A student asks peers to challenge online harassment.','|If we all stay silent, who will speak for the person being targeted?|','The question challenges passive bystanders and presents speaking up as a shared responsibility.']]},
 {id:'alliteration',name:'Alliteration',definition:'Repeats initial consonant sounds in nearby words; the sound matters, not simply the spelling.',contrast:'anaphora',distinction:'Initial sounds recur across nearby words, rather than whole openings across successive clauses.',examples:[
 ['A campaign advertises improvements to a neglected public space.','Help us build |safer, brighter, better| streets.','The repeated initial sound in “brighter, better” links two positive promises and gives the campaign wording a memorable pattern.'],
 ['A narrator notices whispering classmates.','Behind me came |secretive, spiteful whispers|.','The repeated initial sound in “secretive, spiteful” links secrecy with malice, supporting the narrator’s suspicious interpretation.'],
 ['A speaker praises a community’s response after a flood.','We saw |patient, practical people| helping strangers.','The repeated initial sound groups the positive qualities together, making the speaker’s praise compact and memorable.']]}
 ],
 writing:[
 {id:'library',title:'A shared space',context:'A student speaks to the school council about keeping the library open at lunchtime.',text:'We need a place to think. We need a place to read. We need a place to belong. When the library closes its doors, it closes a bridge between students who might otherwise never meet.',task:'Analyse how the speaker presents the library as valuable to the school community.',model:'The speaker presents the library as meeting shared needs through the anaphora “We need a place”. The movement from thinking and reading to “belong” extends its value beyond academic work. The metaphor of a “bridge” further suggests that the library connects students, supporting the argument that closing it would damage the school community.',focus:'Link the repeated demand and the image of connection to the speaker’s case for keeping the library open.'},
 {id:'arrival',title:'Arriving somewhere new',context:'In a fictional narrative, a teenager enters a new school for the first time.',text:'The corridors watched me through a hundred glass doors. Everyone seemed to know where to go. I had a timetable, a locker and a seat; I did not yet have a place. Then a girl waved, and her greeting felt like sunlight through a closed curtain.',task:'Analyse how the language presents the narrator’s changing feelings.',model:'The personification “The corridors watched me” makes the school seem intimidating and reflects the narrator’s feeling of being exposed. The contrast between having practical arrangements and lacking “a place” suggests that physical inclusion has not yet brought belonging. Finally, the simile comparing the greeting to “sunlight” introduces warmth and relief, marking a change from isolation towards possible connection.',focus:'Explain the change across the passage, rather than listing devices without connecting them.'},
 {id:'flood',title:'Promises after the flood',context:'An editorial criticises the council’s response to repeated flooding.',text:'They promised repairs. They promised protection. They promised a future without fear. Yet this winter, some families counted losses while other families counted profits. Calling the damage “a slight inconvenience” will not put a roof back over anyone’s head.',task:'Analyse how the editorial challenges the council’s response.',model:'The anaphora “They promised” accumulates the council’s commitments, making the contrast with the winter’s losses more pointed. The parallel structures “counted losses” and “counted profits” emphasise the unequal consequences of the flooding. By rejecting the understatement “a slight inconvenience”, the editorial criticises language that minimises residents’ suffering and presents the council’s response as inadequate.',focus:'Distinguish the editorial’s own stance from the dismissive wording it quotes and challenges.'},
 {id:'phone',title:'Putting the phone away',context:'A student newspaper article encourages readers to reconsider constant phone checking.',text:'My phone is a tiny landlord collecting rent from every quiet minute. Yesterday I checked it a million times, or so it felt. I could name every trending video, but I could not remember what my brother had just told me. How much of our attention are we willing to give away?',task:'Analyse how the writer encourages readers to reconsider their phone use. Select the two details that best support your interpretation.',model:'The metaphor of the phone as a “landlord collecting rent” presents attention as a resource being repeatedly taken from the writer. This frames checking the phone as a cost rather than a harmless habit. The final rhetorical question extends that personal experience to “our” attention, inviting readers to reflect on their own choices. The exaggeration about checking also conveys frustration, but a focused analysis need not discuss every device.',focus:'Choose evidence that supports your claim; identifying the largest number of devices is not the aim.'}
 ]
};
