const fs=require('fs'),{JSDOM}=require('jsdom'),assert=require('node:assert/strict');
const dir=__dirname+'/../year6/grammar/simple-past/';
const dom=new JSDOM(fs.readFileSync(dir+'index.html','utf8'),{runScripts:'outside-only',url:'http://localhost/year6/grammar/simple-past/'}),w=dom.window,d=w.document;
for(const f of ['data.js','app.js'])w.eval(fs.readFileSync(dir+f,'utf8'));
let count=0;const ok=(x)=>{assert.ok(x);count++};
const all=w.GRAMMAR_DATA.flatMap(g=>g.items);ok(new Set(all.map(q=>q.id)).size===all.length);
for(const g of w.GRAMMAR_DATA){ok(g.items.length===32);ok(new Set(g.items.map(q=>q.prompt)).size===32);d.querySelector('[data-group="'+g.id+'"]').click();d.querySelector('#short').click();let n=0;while(d.querySelector('#form')){const q=all.find(q=>q.id===d.querySelector('.task').dataset.questionId);ok(q);if(q.prompt.includes(' / ')){ok(d.querySelectorAll('.sentence-pieces li').length>1);ok(d.querySelector('.task-note').textContent==='Keep the given subject.');}else{ok(d.querySelector('.task-material'));}d.querySelector('#answer').value=q.answers[0].replace("didn't",'did not').replace("wasn't",'was not').replace("weren't",'were not');d.querySelector('#form').dispatchEvent(new w.Event('submit',{cancelable:true}));ok(d.querySelector('#feedback strong').textContent==='Richtig!');d.querySelector('#next').click();ok(++n<=12);}ok(d.querySelector('h2').textContent==='12 / 12 beim ersten Versuch richtig');d.querySelector('#home').click();}
d.querySelector('#mixed').click();let n=0;while(d.querySelector('#reveal')){d.querySelector('#reveal').click();d.querySelector('#reveal').click();d.querySelector('#next').click();ok(++n<=24);}ok(n===24);ok(d.querySelector('h2').textContent==='0 / 12 beim ersten Versuch richtig');ok(w.localStorage.getItem('vt6:grammar:simple-past:v1'));
d.querySelector('#home').click();d.querySelector('[data-group="regular"]').click();d.querySelector('#start').click();let full=0;while(d.querySelector('#form')){const q=all.find(q=>q.id===d.querySelector('.task').dataset.questionId);d.querySelector('#answer').value=q.answers[0];d.querySelector('#form').dispatchEvent(new w.Event('submit',{cancelable:true}));d.querySelector('#next').click();ok(++full<=32);}ok(full===32);
console.log(count+' grammar checks passed; '+all.length+' original tasks.');
