const fs=require('fs'),vm=require('vm'),{JSDOM}=require('jsdom'),assert=require('assert');
for(const year of ['year5','year6','year7','year8','year9','year10','oberstufe']){
 const html=fs.readFileSync(year+'/index.html','utf8'),dom=new JSDOM(html,{runScripts:'outside-only',url:'https://example.org/'+year+'/'}),w=dom.window,c=dom.getInternalVMContext();w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.dispatchEvent(new w.Event('close'))};
 for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))if(m[1].trim())vm.runInContext(m[1],c);vm.runInContext(fs.readFileSync('assets/learning.js','utf8'),c);
 const d=w.document;d.querySelector('#allBtn').click();const button=d.querySelector('#promptFromSelection');assert(button.disabled);d.querySelector('#lcsv').click();d.querySelector('[data-csv-group]').click();assert(!button.disabled);button.click();const form=d.querySelector('#promptConfig'),count=d.querySelector('#promptCount');
 /* Der Hinweis zur Zaehlweise gehoert zu Opposites und darf nur dann
    dastehen, wenn Opposites auch gewaehlt ist. */
 const hint=d.querySelector('#promptCountHint');
 assert(hint,'Hinweis zur Zaehlweise fehlt');
 assert(hint.hidden,'Hinweis steht da, obwohl Opposites nicht gewaehlt ist');
 assert(/gesuchte Gegenteil/.test(hint.textContent));
 d.querySelector('[value=opposites]').checked=true;d.querySelector('#promptBalance').click();
 assert(!hint.hidden,'Hinweis fehlt, obwohl Opposites gewaehlt ist');
 d.querySelector('[value=opposites]').checked=false;d.querySelector('#promptBalance').click();
 assert(hint.hidden,'Hinweis bleibt stehen, nachdem Opposites abgewaehlt wurde');
 count.value='5';d.querySelector('#promptBalance').click();form.dispatchEvent(new w.Event('submit',{cancelable:true}));let prompt=d.querySelector('#promptText').value;assert(prompt.includes('genau 5'));assert(prompt.includes('Total: / 5'));assert(prompt.includes(year==='oberstufe'?'Einführungsphase (E)':'Klasse '+year.replace('year','')));assert(prompt.includes(['year5','year6'].includes(year)?'deutschen Begriffen':'ohne Word Bank'));assert(prompt.includes(['year5','year6'].includes(year)?'in der Word Bank, in der Aufgabenstellung':'Ihre Nennung in der Aufgabenstellung'));if(year==='oberstufe'){d.querySelector('#promptStage').value='Q2';d.querySelector('#promptBalance').click();form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptText').value.includes('Oberstufe – Q2'));}assert(prompt.includes('zwei getrennte'));assert(prompt.includes('Read each definition and write the matching word on the line.'));assert(!prompt.includes('keine Buchstaben A–F'));assert(prompt.includes('KEINE Zuordnungsaufgabe'));assert(prompt.includes('EINER einzigen Zeile'));assert(prompt.includes('fett UND kursiv'));assert(!prompt.includes('NICHT auf dem Testblatt'));assert(!prompt.includes('mische die Zuordnung'));assert(!prompt.includes('2 × N verschiedene Listeneinträge'));assert(!prompt.includes('Bei jedem Opposites-Paar'));assert(prompt.includes('Definition-Matching enthält nur Definitionen'));assert(prompt.includes('Aufbau: {"Unit": [["Englisch","Deutsch","Wortart"]'));assert(/\["[^"]+","[^"]*","(noun|verb|adjective|adverb|phrase)/.test(prompt));assert(prompt.includes('Jede Definition darf auf genau ein Wort der Auswahl passen'));assert(prompt.includes('britische wie amerikanische Schreibweise'));assert(prompt.includes('subway und nicht subway (AE)'));assert(prompt.includes('derselben Wortfamilie'));assert(prompt.includes('nummerierten Liste der gewählten Zielwörter'));assert(prompt.includes('einheitlich britisch'));assert(!prompt.includes('"Englisch": '));assert(!prompt.includes('verteile den Rest'));assert(!prompt.includes('- Opposites:'));
 count.value=Number(count.max)+1;d.querySelector('#promptBalance').click();form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptError').textContent);
 count.value=5;d.querySelectorAll('[name=taskType]').forEach(i=>i.checked=false);d.querySelector('#promptBalance').click();form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptError').textContent.includes('mindestens einen'));
 d.querySelector('[value=opposites]').checked=true;d.querySelector('#promptBalance').click();form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptText').value.includes('ausschließlich Opposites'));assert(d.querySelector('#promptText').value.includes('Sowohl das vorgegebene Wort als auch das gesuchte Gegenteil'));assert(d.querySelector('#promptText').value.includes('Erstelle noch keinen Test'));assert(d.querySelector('#promptText').value.includes('2 × N verschiedene Listeneinträge'));assert(d.querySelector('#promptText').value.includes('Bei jedem Opposites-Paar'));assert(!d.querySelector('#promptText').value.includes('Definition-Matching enthält nur Definitionen'));assert(!d.querySelector('#promptText').value.includes('Word Bank beim Gap-Filling'));assert(d.querySelector('#promptText').value.includes('gradierbare Adjektive'));d.querySelector('#promptClose').click();assert(!d.querySelector('dialog'));dom.window.close();
}
console.log('All years prompt: scope, quantity, types, required rules, conditional hint and closing passed');
