const fs=require('fs'),vm=require('vm'),{JSDOM}=require('jsdom'),assert=require('assert');
for(const year of ['year5','year6','year7','year8','year9','year10','oberstufe']){
 const html=fs.readFileSync(year+'/index.html','utf8'),dom=new JSDOM(html,{runScripts:'outside-only',url:'https://example.org/'+year+'/'}),w=dom.window,c=dom.getInternalVMContext();w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.dispatchEvent(new w.Event('close'))};
 for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))if(m[1].trim())vm.runInContext(m[1],c);vm.runInContext(fs.readFileSync('assets/learning.js','utf8'),c);
 const d=w.document;d.querySelector('#allBtn').click();const button=d.querySelector('#promptFromSelection');assert(button.disabled);d.querySelector('#lcsv').click();d.querySelector('[data-csv-group]').click();assert(!button.disabled);button.click();const form=d.querySelector('#promptConfig'),count=d.querySelector('#promptCount');
 count.value='5';form.dispatchEvent(new w.Event('submit',{cancelable:true}));let prompt=d.querySelector('#promptText').value;assert(prompt.includes('genau 5'));assert(prompt.includes('Total: / 5'));assert(prompt.includes(year==='oberstufe'?'Einführungsphase (E)':'Klasse '+year.replace('year','')));assert(prompt.includes(['year5','year6'].includes(year)?'deutschen Begriffen':'ohne Word Bank'));if(year==='oberstufe'){d.querySelector('#promptStage').value='Q2';form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptText').value.includes('Oberstufe – Q2'));}assert(prompt.includes('zwei getrennte'));assert(!prompt.includes('- Opposites:'));
 count.value=Number(count.max)+1;form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptError').textContent);
 count.value=5;d.querySelectorAll('[name=taskType]').forEach(i=>i.checked=false);form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptError').textContent.includes('mindestens einen'));
 d.querySelector('[value=opposites]').checked=true;form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert(d.querySelector('#promptText').value.includes('ausschließlich Opposites'));d.querySelector('#promptClose').click();assert(!d.querySelector('dialog'));dom.window.close();
}
console.log('All years prompt: scope, quantity, types, required rules and closing passed');
