(function(){
'use strict';
const {devices,writing}=window.ANALYSIS_DATA, app=document.getElementById('app');
const KEY='vt:analysis:v1', DAY=86400000;
let saved={version:1,results:{},drafts:{},checks:{}},persistent=true;
const valid=o=>o&&o.version===1&&['results','drafts','checks'].every(k=>o[k]&&typeof o[k]==='object'&&!Array.isArray(o[k]))&&Object.values(o.results).every(r=>r&&Number.isFinite(r.attempts)&&Number.isFinite(r.correct)&&Number.isFinite(r.due))&&Object.values(o.drafts).every(x=>typeof x==='string'&&x.length<=15000)&&Object.values(o.checks).every(x=>Array.isArray(x)&&x.every(v=>typeof v==='boolean'));
try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(!valid(p))throw Error('Invalid backup');saved=p;}}catch(e){persistent=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));persistent=true;}catch(e){persistent=false;}document.getElementById('storage').textContent=persistent?'Saved in this browser.':'Browser storage is unavailable. Save a backup before leaving.';}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const normal=s=>s.toLowerCase().trim().replace(/[-_]/g,' ').replace(/\s+/g,' ');
let mode='identify',focus='all',queue=[],index=0,score=0,retried=new Set(),answer=null,initial=0,currentOptions=[];
const questions=[];
for(const d of devices){questions.push({id:d.id+':terms',kind:'terms',d});questions.push({id:d.id+':distinguish',kind:'distinguish',d});d.examples.forEach((e,i)=>{for(const kind of ['identify','effect'])questions.push({id:d.id+':'+i+':'+kind,kind,d,e});});}
const group=q=>q.kind==='terms'?'terms':q.kind==='effect'?'effect':'identify';
function stat(kind){const qs=questions.filter(q=>group(q)===kind);return qs.filter(q=>saved.results[q.id]?.lastCorrect).length+'/'+qs.length;}
function show(html){app.innerHTML=html;const title=app.querySelector('h1');if(title){title.tabIndex=-1;title.focus();}}
function home(){
show('<h1>From spotting devices<br>to explaining meaning.</h1><p class="intro">Build your terminology, identify evidence and explain what language does in its context. Then use your observations in a short analysis.</p><div class="stats"><span>Terms · '+stat('terms')+'</span><span>Recognition · '+stat('identify')+'</span><span>Function · '+stat('effect')+'</span></div><p class="pill">Counts show questions answered correctly on your latest attempt, not a grade for writing.</p><label for="focus">Choose your focus</label><select id="focus"><option value="all">All 12 devices</option>'+devices.map(d=>'<option value="'+d.id+'">'+d.name+'</option>').join('')+'</select><div class="grid"><section class="panel"><h2>Learn</h2><p>Recall the term from its definition. Use the reference cards when you need help.</p><button data-start="terms" class="primary">Recall the terms</button></section><section class="panel"><h2>Practise</h2><p>Six questions per round, with up to one retry for each mistake.</p><div class="actions"><button data-start="identify">Identify</button><button data-start="distinguish">Tell them apart</button><button data-start="effect">Explain the function</button></div></section><section class="panel"><h2>Write</h2><p>Four guided mini-analyses with saved drafts, optional support and model answers.</p><button id="write">Choose a writing task</button></section></div><section class="panel"><h2>Device reference</h2><p>Effects depend on context. A passage can contain more than one device.</p>'+devices.map(d=>'<details><summary>'+d.name+'</summary><p>'+esc(d.definition)+'</p><p class="quote">'+esc(d.examples[0][1].replaceAll('|',''))+'</p><p>'+esc(d.examples[0][2])+'</p><p><strong>Look closely:</strong> '+esc(d.distinction)+'</p></details>').join('')+'</section>');
document.getElementById('focus').value=focus;document.getElementById('focus').onchange=e=>focus=e.target.value;
app.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));document.getElementById('write').onclick=writeHome;
}
function start(kind){mode=kind;let pool=questions.filter(q=>q.kind===kind&&(focus==='all'||q.d.id===focus));const due=pool.filter(q=>!saved.results[q.id]||saved.results[q.id].due<=Date.now());queue=shuffle(due.length?due:pool).slice(0,6);initial=queue.length;index=0;score=0;retried=new Set();answer=null;renderQuestion();}
function renderQuestion(){
if(index>=queue.length){show('<h1>Round complete</h1><section class="panel"><h2>'+score+' of '+queue.length+' answers correct</h2><p>'+initial+' starting questions · '+retried.size+' additional attempts</p><p>Use a new example next time. Being able to explain your evidence matters more than recognising a familiar sentence.</p><div class="actions"><button id="again" class="primary">Another round</button><button id="home">Analysis Skills</button></div></section>');document.getElementById('again').onclick=()=>start(mode);document.getElementById('home').onclick=home;return;}
const q=queue[index],d=q.d;let prompt='',body='';
if(q.kind==='terms'){prompt='Which device does this define?';body='<p class="quote">'+esc(d.definition)+'</p>';}
if(q.kind==='identify'){prompt='Name the device in the highlighted wording.';const parts=q.e[1].split('|');body='<p class="context">'+esc(q.e[0])+'</p><p class="quote">'+esc(parts[0])+'<mark>'+esc(parts[1])+'</mark>'+esc(parts[2])+'</p><p>Choose the most specific term that fits. Related valid terms receive an explanation.</p>';}
if(q.kind==='distinguish'){prompt='Which term matches this distinction?';body='<p class="quote">'+esc(d.distinction)+'</p>';currentOptions=shuffle([{text:d.name,right:true},{text:devices.find(x=>x.id===d.contrast).name,right:false}]);}
if(q.kind==='effect'){prompt='Which explanation is best supported by this passage?';body='<p class="context">'+esc(q.e[0])+'</p><p class="quote">'+esc(q.e[1].replaceAll('|',''))+'</p>';currentOptions=shuffle([{text:q.e[2],right:true},{text:'The wording makes the passage interesting and attracts attention.',right:false,why:'This is too general: it does not explain what this particular wording suggests in this context.'},{text:'This device always produces the same response, regardless of the situation.',right:false,why:'A device does not have a fixed effect. Its function depends on the words, context and purpose.'},{text:'The wording proves that every reader will agree with the writer.',right:false,why:'A text can invite a response, but the passage does not prove how every reader will react.'}]);}
show('<button id="back">← Analysis Skills</button><h1>'+prompt+'</h1><p class="pill">'+(index+1)+' of '+queue.length+' · '+(q.kind==='effect'?'Function':q.kind==='terms'?'Terms':'Recognition')+'</p><progress class="progress" value="'+index+'" max="'+queue.length+'" aria-label="Round progress"></progress><section class="panel">'+body+(q.kind==='terms'||q.kind==='identify'?'<form id="form"><label for="term">Device name</label><input id="term" autocomplete="off" spellcheck="false" maxlength="80"><button class="primary" type="submit">Check answer</button><button type="button" id="reveal">Show answer</button></form>':'<div class="options">'+currentOptions.map((o,i)=>'<button data-option="'+i+'">'+esc(o.text)+'</button>').join('')+'</div>')+'<div id="feedback" role="status"></div></section>');
document.getElementById('back').onclick=home;
const form=document.getElementById('form');if(form){form.onsubmit=e=>{e.preventDefault();const v=document.getElementById('term').value.trim();if(!v||answer!==null)return;const aliases=[d.name,...(d.aliases||[])];if(q.kind==='identify'&&['personification','litotes'].includes(d.id))aliases.push(d.contrast);if(q.kind==='identify'&&d.id==='anaphora')aliases.push('parallelism','repetition');grade(aliases.some(x=>normal(x)===normal(v)),null);};document.getElementById('reveal').onclick=()=>grade(false,null);}
app.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{const o=currentOptions[Number(b.dataset.option)];grade(o.right,o.why);});
}
function grade(right,why){if(answer!==null)return;answer=right;const q=queue[index],r=saved.results[q.id]||{attempts:0,correct:0,due:0};r.attempts++;if(right){r.correct++;score++;}r.lastCorrect=right;r.due=Date.now()+(right?Math.min(7,Math.max(1,r.correct))*DAY:0);saved.results[q.id]=r;save();
if(!right&&!retried.has(q.id)){retried.add(q.id);queue.splice(Math.min(index+4,queue.length),0,q);}
app.querySelectorAll('#form button,#term,[data-option]').forEach(b=>b.disabled=true);
app.querySelectorAll('[data-option]').forEach((b,i)=>{if(currentOptions[i].right)b.classList.add('correct');});
document.getElementById('feedback').innerHTML='<div class="feedback"><strong>'+(right?'Supported answer.':'Review the evidence.')+'</strong><p><strong>'+esc(q.d.name)+':</strong> '+esc(q.d.definition)+'</p><p>'+esc(why||(q.kind==='effect'?q.e[2]:q.d.distinction))+'</p>'+(q.kind==='identify'?'<p>'+esc(q.e[2])+'</p>':'')+'<button id="next" class="primary">Continue</button></div>';
document.getElementById('next').onclick=()=>{index++;answer=null;renderQuestion();};document.getElementById('next').focus();}
function writeHome(){show('<button id="back">← Analysis Skills</button><h1>Write a mini-analysis</h1><p>Make a claim, support it with precise evidence and explain how the wording supports your interpretation.</p>'+writing.map(w=>'<section class="panel"><h2>'+w.title+'</h2><p>'+esc(w.context)+'</p><button data-write="'+w.id+'">'+(saved.drafts[w.id]?'Continue draft':'Start writing')+'</button></section>').join(''));document.getElementById('back').onclick=home;app.querySelectorAll('[data-write]').forEach(b=>b.onclick=()=>writeTask(b.dataset.write));}
const criteria=['I answer the specific task, rather than list devices.','I quote precise evidence and name a relevant technique accurately.','I explain what the wording suggests in this context.','I connect my observations to a supported interpretation.'];
function writeTask(id){const w=writing.find(x=>x.id===id);show('<button id="back">← Writing tasks</button><h1>'+w.title+'</h1><p class="context">'+esc(w.context)+'</p><section class="panel"><p class="quote">'+esc(w.text)+'</p><h2>Your task</h2><p>'+esc(w.task)+'</p><p>Write three to five analytical sentences. More than one interpretation may be supported.</p><details><summary>Help me structure my answer</summary><p>The writer presents … as … . The phrase “…” suggests … because … . This supports/challenges … .</p><p>'+esc(w.focus)+'</p></details><label for="draft">Your analysis</label><textarea id="draft" maxlength="15000">'+esc(saved.drafts[id]||'')+'</textarea><p id="draftStatus" role="status">Drafts are saved as you write.</p><button id="compare">Compare with one possible answer</button><div id="model"></div><h2>Check your reasoning</h2>'+criteria.map((c,i)=>'<label class="check"><input type="checkbox" data-check="'+i+'" '+(saved.checks[id]?.[i]?'checked':'')+'>'+c+'</label>').join('')+'<p class="muted">This is self-assessment, not an automatic grade. Different wording and other well-supported interpretations can be valid.</p></section>');document.getElementById('back').onclick=writeHome;document.getElementById('draft').oninput=e=>{saved.drafts[id]=e.target.value;save();document.getElementById('draftStatus').textContent=persistent?'Draft saved.':'Draft kept for this session. Save a backup before leaving.';};document.getElementById('compare').onclick=()=>{if(!(saved.drafts[id]||'').trim()){document.getElementById('draftStatus').textContent='Try writing your own interpretation first.';return;}document.getElementById('model').innerHTML='<div class="feedback"><h3>One possible answer</h3><p class="model">'+esc(w.model)+'</p><p>'+esc(w.focus)+'</p><p>Compare the reasoning and evidence, not whether your wording matches.</p></div>';};app.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{saved.checks[id]=criteria.map((_,i)=>app.querySelector('[data-check="'+i+'"]').checked);save();});}
document.getElementById('backup').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(saved)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='analysis-skills-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.getElementById('restore').onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error();const p=JSON.parse(await f.text());if(!valid(p))throw Error();saved.results={...saved.results,...p.results};saved.drafts={...saved.drafts,...p.drafts};saved.checks={...saved.checks,...p.checks};save();home();}catch(err){document.getElementById('storage').textContent='This is not a valid Analysis Skills backup. Your current work has been kept.';}e.target.value='';};
home();if(!persistent)document.getElementById('storage').textContent='Saved data could not be read. Save a backup of new work before leaving.';
})();
