(function(){
'use strict';
const groups=window.GRAMMAR_DATA,app=document.getElementById('app'),key='vt6:grammar:simple-past:v1';
let results={},queue=[],at=0,correct=0,locked=false,current='mixed',missed=[],initial=0;
try{const x=JSON.parse(localStorage.getItem(key)||'{}');if(x&&typeof x==='object'&&!Array.isArray(x))results=Object.fromEntries(Object.entries(x).filter(([k,v])=>groups.some(g=>g.items.some(q=>q.id===k))&&typeof v==='boolean'));}catch(e){document.getElementById('storage').textContent='Storage is unavailable. You can still practise.';}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=s=>s.toLowerCase().replace(/[’‘]/g,"'").replace(/didn't/g,'did not').replace(/wasn't/g,'was not').replace(/weren't/g,'were not').replace(/[.,?!]/g,'').replace(/\s+/g,' ').trim();
const shuffle=a=>a.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(o=>o.x);
function show(html){app.innerHTML=html;const h=app.querySelector('h1');h.tabIndex=-1;h.focus();}
function home(){show('<h1>Simple past</h1><p>Talk about things that happened in the past. Choose a skill or try a mixed round.</p><button id="mixed" class="primary">Mixed practice · 12 questions</button><div class="grid">'+groups.map(g=>'<button class="panel" data-group="'+g.id+'"><h2>'+g.title+'</h2><p>'+g.items.filter(q=>results[q.id]===true).length+' / '+g.items.length+' correct on latest attempts</p><progress value="'+g.items.filter(q=>results[q.id]===true).length+'" max="32" aria-label="Progress in '+esc(g.title)+'"></progress><span>Learn & practise →</span></button>').join('')+'</div><p>Each round has twelve questions. Review mistakes once at the end. Scores describe your practice, not a school grade.</p>');app.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>lesson(b.dataset.group));document.getElementById('mixed').onclick=()=>start('mixed');}
function lesson(id){const g=groups.find(g=>g.id===id);show('<button id="home">← Skills</button><h1>'+g.title+'</h1><section class="panel"><h2>Remember</h2><p>'+esc(g.rule)+'</p><p class="quote">'+esc(g.example)+'</p>'+(id==='regular'?'<p>British English: travel → travelled. American English: travel → traveled. After /t/ or /d/, -ed adds a syllable: wanted, needed. Otherwise, -ed is /t/ (washed) or /d/ (played).</p>':'')+'<button id="start" class="primary">Practise · 12 questions</button></section>');document.getElementById('home').onclick=home;document.getElementById('start').onclick=()=>start(id);}
function start(id){current=id;const pool=id==='mixed'?groups.flatMap(g=>g.items):groups.find(g=>g.id===id).items;queue=[...shuffle(pool.filter(q=>results[q.id]!==true)),...shuffle(pool.filter(q=>results[q.id]===true))].slice(0,12).map(q=>({...q,retry:false}));initial=queue.length;at=0;correct=0;missed=[];question();}
function question(){locked=false;if(at>=queue.length)return done();const q=queue[at];show('<button id="home">← Skills</button><h1>'+(q.retry?'Try it again':'Your turn')+'</h1><p>'+(at+1)+' of '+queue.length+'</p><progress value="'+at+'" max="'+queue.length+'" aria-label="Round progress"></progress><section class="panel"><p class="task">'+esc(q.prompt)+'</p><form id="form"><label for="answer">Your answer</label><input id="answer" autocomplete="off" spellcheck="false" maxlength="300" required><button class="primary">Check answer</button> <button type="button" id="reveal">Show answer</button></form><details><summary>Give me a hint</summary><p>'+esc(q.hint)+'</p></details><div id="feedback" role="status"></div></section>');document.getElementById('home').onclick=home;document.getElementById('form').onsubmit=e=>{e.preventDefault();grade(false);};document.getElementById('reveal').onclick=()=>grade(true);}
function grade(reveal){if(locked)return;const q=queue[at],input=document.getElementById('answer'),value=input.value;if(!reveal&&!value.trim())return;locked=true;const right=!reveal&&q.answers.some(a=>normal(a)===normal(value));results[q.id]=right;if(right&&!q.retry)correct++;if(!right&&!q.retry){missed.push(q);queue.push({...q,retry:true});}try{localStorage.setItem(key,JSON.stringify(results));document.getElementById('storage').textContent='Progress saved in this browser.';}catch(e){document.getElementById('storage').textContent='Progress could not be saved. You can continue this round.';}app.querySelectorAll('#form button,#answer').forEach(b=>b.disabled=true);document.getElementById('feedback').innerHTML='<div class="feedback '+(right?'feedback-correct':'feedback-review')+'"><strong>'+(right?'Correct!':reveal?'Study the answer.':'Not quite yet.')+'</strong><p class="answer">'+esc(q.answers[0])+'</p><p>'+esc(q.hint)+'</p>'+(!right&&!q.retry?'<p>You will try this question again at the end.</p>':'')+'<button id="next" class="primary">Continue</button></div>';document.getElementById('next').onclick=()=>{at++;question();};document.getElementById('next').focus();}
function done(){show('<h1>Round complete</h1><section class="panel"><h2>'+correct+' / '+initial+' correct first time</h2><p>'+missed.filter(q=>results[q.id]).length+' / '+missed.length+' mistakes corrected on retry.</p><div class="actions"><button id="again" class="primary">Another round</button><button id="home">Choose a skill</button></div></section>'+(missed.length?'<h2>Keep practising</h2><ul class="summary-list">'+missed.map(q=>'<li>'+esc(q.prompt)+'<br><strong>'+esc(q.answers[0])+'</strong></li>').join('')+'</ul>':''));document.getElementById('again').onclick=()=>start(current);document.getElementById('home').onclick=home;}
home();
})();
