(function(){
'use strict';
const groups=window.GRAMMAR_DATA,app=document.getElementById('app'),key='vt6:grammar:simple-past:v1';
let results={},queue=[],at=0,correct=0,locked=false,current='mixed',missed=[],initial=0,limit=32;
try{const x=JSON.parse(localStorage.getItem(key)||'{}');if(x&&typeof x==='object'&&!Array.isArray(x))results=Object.fromEntries(Object.entries(x).filter(([k,v])=>groups.some(g=>g.items.some(q=>q.id===k))&&typeof v==='boolean'));}catch(e){document.getElementById('storage').textContent='Speicher nicht verfügbar. Du kannst trotzdem üben.';}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=s=>s.toLowerCase().replace(/[’‘]/g,"'").replace(/didn't/g,'did not').replace(/wasn't/g,'was not').replace(/weren't/g,'were not').replace(/[.,?!]/g,'').replace(/\s+/g,' ').trim();
const shuffle=a=>a.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(o=>o.x);
function show(html){const label=groups.find(g=>g.id===current)?.title;app.innerHTML='<nav class="breadcrumb" aria-label="Navigationspfad"><a href="../../">Year 6</a><span>›</span><a href="../">Grammar</a><span>›</span><span>Simple Past</span></nav>'+html;const h=app.querySelector('h1');h.tabIndex=-1;h.focus();}
function home(){show('<h1>Simple past</h1><p>Übe, über Vergangenes zu sprechen. Wähle eine Kategorie oder eine gemischte Runde.</p><button id="mixed" class="primary">Gemischt üben · 12 Aufgaben</button><div class="grid">'+groups.map(g=>'<button class="panel" data-group="'+g.id+'"><h2>'+g.title+'</h2><p>'+g.items.filter(q=>results[q.id]===true).length+' / '+g.items.length+' zuletzt richtig beantwortet</p><progress value="'+g.items.filter(q=>results[q.id]===true).length+'" max="32" aria-label="Progress in '+esc(g.title)+'"></progress><span>Lernen und üben →</span></button>').join('')+'</div><p>Jede Kategorie enthält 32 Aufgaben. Du kannst alle 32 Aufgaben oder eine kurze Runde mit zwölf Aufgaben wählen. Falsche Antworten wiederholst du am Ende einmal. Die Ergebnisse zeigen deinen Übungsstand und sind keine Schulnote.</p>');app.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>lesson(b.dataset.group));document.getElementById('mixed').onclick=()=>{limit=12;start('mixed');};}
function lesson(id){const g=groups.find(g=>g.id===id);show('<button id="home">← Kategorien</button><h1>'+g.title+'</h1><section class="panel"><h2>Die Regel</h2><p>'+esc(g.rule)+'</p><p class="quote">'+esc(g.example)+'</p>'+(id==='regular'?'<p>British English: travel → travelled. American English: travel → traveled. After /t/ or /d/, -ed adds a syllable: wanted, needed. Otherwise, -ed is /t/ (washed) or /d/ (played).</p>':'')+'<div class="actions"><button id="start" class="primary">Alle 32 Aufgaben üben</button><button id="short">Kurze Runde · 12 Aufgaben</button></div><label for="linkSize">Lernumfang für den Hausaufgaben-Link</label><select id="linkSize"><option value="32">Alle 32 Aufgaben</option><option value="12">Kurze Runde · 12 Aufgaben</option></select><button id="share">Hausaufgaben-Link anzeigen</button><div id="shareResult"></div></section>');document.getElementById('home').onclick=home;document.getElementById('start').onclick=()=>{limit=32;start(id);};document.getElementById('short').onclick=()=>{limit=12;start(id);};const requested=new URLSearchParams(location.search).get('count');if(['12','32'].includes(requested))document.getElementById('linkSize').value=requested;
 document.getElementById('share').onclick=()=>{const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('category',id);u.searchParams.set('count',document.getElementById('linkSize').value);document.getElementById('shareResult').innerHTML='<label for="assignmentURL">Link kopieren und weitergeben</label><input id="assignmentURL" readonly>';const input=document.getElementById('assignmentURL');input.value=u.href;input.focus();input.select();};
 if(requested==='12'){document.getElementById('short').classList.add('primary');document.getElementById('start').classList.remove('primary');}
}
function start(id){current=id;const pool=id==='mixed'?groups.flatMap(g=>g.items):groups.find(g=>g.id===id).items;queue=[...shuffle(pool.filter(q=>results[q.id]!==true)),...shuffle(pool.filter(q=>results[q.id]===true))].slice(0,limit).map(q=>({...q,retry:false}));initial=queue.length;at=0;correct=0;missed=[];question();}
function question(){locked=false;if(at>=queue.length)return done();const q=queue[at];show('<button id="home">← Kategorien</button><h1>'+(q.retry?'Noch einmal versuchen':'Du bist dran')+'</h1><p>'+(at+1)+' von '+queue.length+'</p><progress value="'+at+'" max="'+queue.length+'" aria-label="Fortschritt der Runde"></progress><section class="panel"><p class="task">'+esc(q.prompt)+'</p><form id="form"><label for="answer">Deine Antwort</label><input id="answer" autocomplete="off" spellcheck="false" maxlength="300" required><button class="primary">Antwort prüfen</button> <button type="button" id="reveal">Lösung zeigen</button></form><details><summary>Tipp anzeigen</summary><p>'+esc(q.hint)+'</p></details><div id="feedback" role="status"></div></section>');document.getElementById('home').onclick=home;document.getElementById('form').onsubmit=e=>{e.preventDefault();grade(false);};document.getElementById('reveal').onclick=()=>grade(true);}
function grade(reveal){if(locked)return;const q=queue[at],input=document.getElementById('answer'),value=input.value;if(!reveal&&!value.trim())return;locked=true;const right=!reveal&&q.answers.some(a=>normal(a)===normal(value));results[q.id]=right;if(right&&!q.retry)correct++;if(!right&&!q.retry){missed.push(q);queue.push({...q,retry:true});}try{localStorage.setItem(key,JSON.stringify(results));document.getElementById('storage').textContent='Fortschritt in diesem Browser gespeichert.';}catch(e){document.getElementById('storage').textContent='Speichern nicht möglich. Du kannst in dieser Runde weiterüben.';}app.querySelectorAll('#form button,#answer').forEach(b=>b.disabled=true);document.getElementById('feedback').innerHTML='<div class="feedback '+(right?'feedback-correct':'feedback-review')+'"><strong>'+(right?'Richtig!':reveal?'Schau dir die Lösung an.':'Noch nicht ganz.')+'</strong><p class="answer">'+esc(q.answers[0])+'</p><p>'+esc(q.hint)+'</p>'+(!right&&!q.retry?'<p>Diese Aufgabe kommt am Ende noch einmal.</p>':'')+'<button id="next" class="primary">Weiter</button></div>';document.getElementById('next').onclick=()=>{at++;question();};document.getElementById('next').focus();window.LearningFeedback?.signal(right?'ok':'no');}
function done(){window.LearningFeedback?.tone('done');show('<h1>Runde abgeschlossen</h1><section class="panel"><h2>'+correct+' / '+initial+' beim ersten Versuch richtig</h2><p>'+missed.filter(q=>results[q.id]).length+' / '+missed.length+' Fehler bei der Wiederholung korrigiert.</p><div class="actions"><button id="again" class="primary">Weitere Runde</button><button id="home">Kategorie wählen</button></div></section>'+(missed.length?'<h2>Zum Weiterüben</h2><ul class="summary-list">'+missed.map(q=>'<li>'+esc(q.prompt)+'<br><strong>'+esc(q.answers[0])+'</strong></li>').join('')+'</ul>':''));document.getElementById('again').onclick=()=>start(current);document.getElementById('home').onclick=home;}
const params=new URLSearchParams(location.search);if(groups.some(g=>g.id===params.get('category')))lesson(params.get('category'));else home();
})();
